extends: stylelint-config-primer
rules:
  selector-no-type: [ true, {
    ignoreTypes: [ html, body, a ]
  }]
  declaration-block-properties-order:
    - position
    - top
    - right
    - bottom
    - left
    - z-index
    - display
    - visibility
    - zoom
    - float
    - clear
    - flex-direction
    - flex-order
    - flex-pack
    - flex-align
    - box-sizing
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    - width
    - min-width
    - max-width
    - height
    - min-height
    - max-height
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    - outline
    - outline-width
    - outline-style
    - outline-color
    - outline-offset
    - border
    - border-color
    - border-style
    - border-width
    - border-top
    - border-top-color
    - border-top-style
    - border-top-width
    - border-right
    - border-right-color
    - border-right-style
    - border-right-width
    - border-bottom
    - border-bottom-color
    - border-bottom-style
    - border-bottom-width
    - border-left
    - border-left-color
    - border-left-style
    - border-left-width
    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-right-radius
    - border-bottom-left-radius
    - border-image
    - border-image-source
    - border-image-slice
    - border-image-width
    - border-image-outset
    - border-image-repeat
    - border-spacing
    - border-collapse
    - overflow
    - overflow-x
    - overflow-y
    - clip
    - background
    - background-color
    - background-image
    - filter
    - background-repeat
    - background-attachment
    - background-position
    - background-position-x
    - background-position-y
    - background-clip
    - background-origin
    - background-size
    - stroke
    - stroke-opacity
    - stroke-width
    - fill
    - fill-opacity
    - box-shadow
    - opacity
    - vertical-align
    - line-height
    - font
    - font-family
    - font-size
    - font-style
    - font-weight
    - font-variant
    - font-size-adjust
    - font-stretch
    - font-effect
    - font-emphasize
    - font-emphasize-position
    - font-emphasize-style
    - font-smooth
    - hyphens
    - color
    - text-align
    - text-align-last
    - text-emphasis
    - text-emphasis-color
    - text-emphasis-style
    - text-emphasis-position
    - text-decoration
    - text-indent
    - text-justify
    - text-outline
    - text-overflow
    - text-overflow-ellipsis
    - text-overflow-mode
    - text-shadow
    - text-transform
    - text-wrap
    - letter-spacing
    - word-break
    - word-spacing
    - word-wrap
    - tab-size
    - white-space
    - list-style
    - list-style-position
    - list-style-type
    - list-style-image
    - pointer-events
    - shape-rendering
    - cursor
    - table-layout
    - empty-cells
    - caption-side
    - content
    - quotes
    - counter-reset
    - counter-increment
    - resize
    - user-select
    - nav-index
    - nav-up
    - nav-right
    - nav-down
    - nav-left
    - transition
    - transition-delay
    - transition-timing-function
    - transition-duration
    - transition-property
    - transform
    - transform-origin
    - animation
    - animation-name
    - animation-duration
    - animation-fill-mode
    - animation-play-state
    - animation-timing-function
    - animation-delay
    - animation-iteration-count
    - animation-direction
